export const LocationActionTypes = {
  FETCH_LOCATION_START: 'FETCH_LOCATION_START',
  FETCH_LOCATION_SUCCESS: 'FETCH_LOCATION_SUCCESS',
  FETCH_LOCATION_FAILURE: 'FETCH_LOCATION_FAILURE',
  ADD_SELECTED_LOCATION: 'ADD_SELECTED_LOCATION',
  REMOVE_SELECTED_LOCATION: 'REMOVE_SELECTED_LOCATION',
};
